### ISSUE TITLE
About Participation and Ownership

### ISSUE THREAD

**Issue by DrakeW** [KunQian26/Rate-My-GSI#1]
Hey I don't think you can create a new repo and copy paste code here, because this is a teamwork project, and in my repository people can see your participation through your commits. But if you copy and paste code here then this means you are the only owner of this repository and no one shares any contribution. So instead of create this new repo and copy&paste code, please either fork the repo from my account [Rate-My-GSI](https://github.com/DrakeW/Rate-My-GSI) or just leave it there since others can still see the repo you contributed to, and delete this repo. Thanks :)

**Comment by DrakeW** [comment]
And I have re-added you three to the participation so that this repo will be shown in the repository you contributed to!

**Comment by KunQian26** [comment]
I have included all contributors in the project.
